version: '3.8'

services:
  web:
    build: .
    container_name: flask-app
    environment:
      POSTGRES_HOST: prod-best.cv02cigeq69q.eu-west-2.rds.amazonaws.com
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "80:80"